version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    env_file:
      - ./db.env

  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    depends_on: 
      - db
    environment: 
      - SECRET_KEY=django-insecure-_3rmr)&*&97dvt+x)q-zmsx5u=t@ne=_*)u%tcb-cs)7rfl4_@
      - ALLOWED_HOSTS=127.0.0.1,localhost
    env_file:
      - ./db.env
  
  proxy:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    volumes:
      - static_data:/vol/static
    depends_on:
      - app

volumes:
  static_data: