version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    env_file:
      - ./db.env

  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./django-core:/django-core
    depends_on: 
      - db
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    env_file:
      - ./db.env
